# PBLHTSONDE1MCFARL.C1 Plots

[Click here](https://www.arm.gov/capabilities/vaps/pblht) for more information about this vap.

In [1]:
%matplotlib widget
import ipywidgets as widgets

import matplotlib.pyplot as plt
import ipywidgets as widgets
import numpy as np
import pandas as pd
import os
from datetime import datetime

import act
import xarray as xr

# Data archive directory
DATA_DIR = r'/data/archive/'

# Datastream info
DATASTREAM_NAME = 'pblhtsonde1mcfarl'
DATA_LEVEL = 'c1'
LOCATIONS = [{'end_date': '2017-01-02', 'facility': 'M1', 'site': 'awr', 'start_date': '2015-11-30'}, {'end_date': '2016-01-18', 'facility': 'S1', 'site': 'awr', 'start_date': '2015-12-01'}, {'end_date': '2017-10-31', 'facility': 'S1', 'site': 'asi', 'start_date': '2016-04-29'}, {'end_date': '2015-02-09', 'facility': 'M1', 'site': 'acx', 'start_date': '2015-01-12'}, {'end_date': '2020-05-31', 'facility': 'M1', 'site': 'anx', 'start_date': '2019-12-02'}, {'end_date': '2023-12-12', 'facility': 'C1', 'site': 'nsa', 'start_date': '2002-04-28'}, {'end_date': '2012-03-31', 'facility': 'M1', 'site': 'pgh', 'start_date': '2011-06-15'}, {'end_date': '2013-06-29', 'facility': 'M1', 'site': 'pvc', 'start_date': '2012-06-25'}, {'end_date': '2021-06-14', 'facility': 'M1', 'site': 'oli', 'start_date': '2013-10-03'}, {'end_date': '2020-10-01', 'facility': 'M1', 'site': 'mos', 'start_date': '2019-10-11'}, {'end_date': '2015-12-01', 'facility': 'M1', 'site': 'mao', 'start_date': '2014-01-01'}, {'end_date': '2012-04-08', 'facility': 'M1', 'site': 'gan', 'start_date': '2011-09-15'}, {'end_date': '2011-01-05', 'facility': 'M1', 'site': 'grw', 'start_date': '2009-04-16'}, {'end_date': '2013-10-03', 'facility': 'M1', 'site': 'mag', 'start_date': '2012-10-01'}, {'end_date': '2018-03-24', 'facility': 'M1', 'site': 'mar', 'start_date': '2017-10-31'}, {'end_date': '2023-06-15', 'facility': 'M1', 'site': 'guc', 'start_date': '2021-09-01'}, {'end_date': '2023-12-12', 'facility': 'M1', 'site': 'epc', 'start_date': '2023-02-06'}, {'end_date': '2008-12-28', 'facility': 'M1', 'site': 'hfe', 'start_date': '2008-05-14'}, {'end_date': '2019-04-29', 'facility': 'M1', 'site': 'cor', 'start_date': '2018-09-27'}, {'end_date': '2022-10-01', 'facility': 'M1', 'site': 'hou', 'start_date': '2021-09-18'}, {'end_date': '2022-09-25', 'facility': 'S1', 'site': 'hou', 'start_date': '2021-08-28'}, {'end_date': '2023-12-13', 'facility': 'C1', 'site': 'ena', 'start_date': '2013-09-28'}, {'end_date': '2008-01-01', 'facility': 'M1', 'site': 'fkb', 'start_date': '2007-03-24'}, {'end_date': '2007-01-08', 'facility': 'M1', 'site': 'nim', 'start_date': '2006-01-07'}, {'end_date': '2005-09-15', 'facility': 'M1', 'site': 'pye', 'start_date': '2005-02-25'}, {'end_date': '2011-04-24', 'facility': 'M1', 'site': 'sbs', 'start_date': '2010-11-08'}, {'end_date': '2007-06-13', 'facility': 'B1', 'site': 'sgp', 'start_date': '2002-05-13'}, {'end_date': '2007-06-29', 'facility': 'B4', 'site': 'sgp', 'start_date': '2002-05-20'}, {'end_date': '2007-06-22', 'facility': 'B5', 'site': 'sgp', 'start_date': '2002-05-20'}, {'end_date': '2002-11-26', 'facility': 'B6', 'site': 'sgp', 'start_date': '2001-06-20'}, {'end_date': '2023-12-11', 'facility': 'C1', 'site': 'sgp', 'start_date': '2001-04-01'}, {'end_date': '2014-09-12', 'facility': 'M1', 'site': 'tmp', 'start_date': '2014-02-01'}, {'end_date': '2014-07-07', 'facility': 'C1', 'site': 'twp', 'start_date': '2001-04-03'}, {'end_date': '2013-08-25', 'facility': 'C2', 'site': 'twp', 'start_date': '2001-04-01'}, {'end_date': '2015-01-14', 'facility': 'C3', 'site': 'twp', 'start_date': '2002-04-28'}]

## Define site, facility, and date range

In [2]:
print("The following locations and date ranges are available for this VAP:")
display(pd.DataFrame(LOCATIONS, columns=['site', 'facility', 'start_date', 'end_date']))

The following locations and date ranges are available for this VAP:

   site facility  start_date    end_date
0   awr       M1  2015-11-30  2017-01-02
1   awr       S1  2015-12-01  2016-01-18
2   asi       S1  2016-04-29  2017-10-31
3   acx       M1  2015-01-12  2015-02-09
4   anx       M1  2019-12-02  2020-05-31
5   nsa       C1  2002-04-28  2023-12-12
6   pgh       M1  2011-06-15  2012-03-31
7   pvc       M1  2012-06-25  2013-06-29
8   oli       M1  2013-10-03  2021-06-14
9   mos       M1  2019-10-11  2020-10-01
10  mao       M1  2014-01-01  2015-12-01
11  gan       M1  2011-09-15  2012-04-08
12  grw       M1  2009-04-16  2011-01-05
13  mag       M1  2012-10-01  2013-10-03
14  mar       M1  2017-10-31  2018-03-24
15  guc       M1  2021-09-01  2023-06-15
16  epc       M1  2023-02-06  2023-12-12
17  hfe       M1  2008-05-14  2008-12-28
18  cor       M1  2018-09-27  2019-04-29
19  hou       M1  2021-09-18  2022-10-01
20  hou       S1  2021-08-28  2022-09-25
21  ena       C1  2013-09-28  2023-12-13
22  fkb       M1  2007-03-24  2008-01-01
23  nim       M1  2006-01-07  2007-01-08
24  pye       M1  2005-02-25  2005-09-15
25  sbs       M1  2010-11-08  2011-04-24
26  sgp       B1  2002-05-13  2007-06-13
27  sgp       B4  2002-05-20  2007-06-29
28  sgp       B5  2002-05-20  2007-06-22
29  sgp       B6  2001-06-20  2002-11-26
30  sgp       C1  2001-04-01  2023-12-11
31  tmp       M1  2014-02-01  2014-09-12
32  twp       C1  2001-04-03  2014-07-07
33  twp       C2  2001-04-01  2013-08-25
34  twp       C3  2002-04-28  2015-01-14

#### Define site, facility, and date range (date format: YYYY-MM-DD) using the variables below:

In [3]:
site_facility = ( 'sgp', 'B1' )

date_start = '2007-06-10'
date_end = '2007-06-12'

## Load data files
Load data files from /data/archive/

In [4]:
# Compile list of files
site, facility = site_facility
d_date_start = datetime.strptime(date_start, '%Y-%m-%d')
d_date_end = datetime.strptime(date_end, '%Y-%m-%d')
dir_path = os.path.join(DATA_DIR + site, site + DATASTREAM_NAME + facility + r'.' + DATA_LEVEL )
dir_path

'/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1'

In [5]:
from datetime import date, timedelta
import pandas as pd

def get_ARM_formated_dates(start_date, end_date):
    """
    Get a list of ARM conventional formated date lists, based on start_date and end_date(inclusive)
    EXAMPLE:
    get_ARM_formated_dates(start_date="20180219", end_date="20180221")
    >> ["20180219", "20180220", "20180221"] 
    """
    
    _start_date = pd.to_datetime(start_date)
    _end_date = pd.to_datetime(end_date)
    
    delta = _end_date - _start_date   # returns timedelta    
    dates = []

    for i in range(delta.days + 1):
        day = _start_date + timedelta(days=i)
        day_formated = day.strftime(format="%Y%m%d")
        dates.append(day_formated)
    return dates


get_ARM_formated_dates(start_date=date_start, end_date=date_end)

['20070610', '20070611', '20070612']

In [6]:
# Filter a list of files based on date pattern
import glob
dates = get_ARM_formated_dates(start_date=date_start, end_date=date_end)
files_filter = []
for date in dates:
    files_filter += glob.glob(f'{dir_path}/*.{date}*.*')
    files_filter
files_filter

['/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070611.150200.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070611.173000.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070611.202900.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070611.232800.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.052900.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.112900.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.143100.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.082900.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.233900.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.173100.cdf',
 '/data/archive/sgp/sgppblhtsonde1mcfarlB1.c1/sgppblhtsonde1mcfarlB1.c1.20070612.023100.cdf']

In [7]:
# Load files as a single dataset
files_list = files_filter 
ds = act.io.armfiles.read_netcdf(files_list)
ds.clean.cleanup()
print(f'{len(files_list)} files loaded')
ds

ValueError: Coordinate variable height_ss is neither monotonically increasing nor monotonically decreasing on all datasets

## Plot time series data
#### Define the list of variables to be plotted:

In [ ]:
variables_to_plot = ['pbl_height_heffter', 'pbl_height_liu_liang', 'pbl_height_bulk_richardson_pt25']

In [ ]:
ts_display = act.plotting.TimeSeriesDisplay(ds)
ts_display.add_subplots((len(variables_to_plot),), figsize = (9.5,4*len(variables_to_plot)))

for i,v in enumerate(variables_to_plot):
    ts_ax = ts_display.plot(v, subplot_index=(i,), set_title=ds.variables[v].attrs['long_name'],)
    ts_ax.grid()

plt.show()

## Field selection dropdown menu
Select variable to be plotted from a dropdown menu

In [ ]:
plt.ioff()

# populate dropdown menu with available variables 
available_variables = [v for v in ds.variables if not('time' in v or v.startswith('qc_') or v.startswith('source_')) and 'long_name' in ds.variables[v].attrs]
d_variable = 'pbl_height_heffter'
dropdown = widgets.Dropdown(
    options = [(ds.variables[v].attrs['long_name'], v) for v in available_variables],
    value= d_variable,
    description='Field:',
    disabled=False,
)
dropdown.layout.margin = '0px 30% 0px 20%'
dropdown.layout.width = '50%'

# set up display
i_display = act.plotting.TimeSeriesDisplay(ds)
i_display.add_subplots((1,), figsize = (9.5,5))
i_ax = i_display.plot(d_variable, subplot_index=(0,), set_title=ds.variables[d_variable].attrs['long_name'],)
i_ax.grid()
i_fig = i_display.fig

# update plot callback function
def update_plot(change):
    i_ax.cla()
    i_ax_new = i_display.plot(change.new, subplot_index=(0,), set_title=ds.variables[change.new].attrs['long_name'],)
    i_ax_new.grid()
    i_fig.canvas.draw()
    i_fig.canvas.flush_events()

dropdown.observe(update_plot, names='value')

widgets.AppLayout(
    header=dropdown,
    center=i_fig.canvas,
    pane_heights=[1, 6,1]
)